version: '3'

services:
  postgresql:
    image: "postgres:9.6.9"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secrets
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
